services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.local
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env
  #   environment:
  #     - NODE_ENV=development
  #     - APP_PORT=3000
  #   depends_on:
  #     - redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379
    environment:
      TZ: Greenwich
    command: redis-server --save "" --maxmemory-policy noeviction --appendonly yes
